### PR TITLE
Remove a floating promise in `autoload`

### LINKED ISSUE #53: Dynamic loading is failed some times
The dynamic load is here:

https://github.com/Shougo/ddu.vim/blob/bd3d1166d884cda76e81d1050d3a8f4e28200782/denops/ddu/ddu.ts#L1408

### PR DESCRIPTION
**Pull request by hasundue**
Hopefully fix #53

### CODE REVIEW

File: denops/ddu/ddu.ts [hunk 1]
```diff
@@ -1403,6 +1403,8 @@ export class Ddu {
     for (const alias of aliases) {
       add(alias);
     }
+
+    return;
```
Comment (Shougo) [inline denops/ddu/ddu.ts:1407]: Why the return is needed?

Comment (hasundue) [reply denops/ddu/ddu.ts:1407]: This may not be needed actually. Just trying to make sure that the resolution of Promise happened in the end of the function.

Comment (Shougo) [reply denops/ddu/ddu.ts:1407]: Please remove the line.

**Comment by Shougo** [comment]
LGTM
